package arbolE;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author oma98
 */
public class FrameLCD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLCD.class.getName());

    // ===== NUEVO =====
    private static final String RUTA_DESTINO = "C:\\LyA 2\\pruebaEmulador";
    private static final int PUERTO_INICIAL = 0x2040;
    private static final int PUERTO_FINAL   = 0x206F;
    /**
     * Creates new form FrameLCD
     */
    public FrameLCD() {
        initComponents();
        
         // NUEVO: corrige el EXIT_ON_CLOSE que trae initComponents()
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    // NUEVO: conecta el botón Exportar (así no se toca initComponents())
    btnExportar.addActionListener(this::btnExportarActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextArchivo = new javax.swing.JTextField();
        jTextEnvio = new javax.swing.JTextField();
        btnExportar = new javax.swing.JButton();
        laHora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/itt_escudo (1).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VID_20260530_080812_746.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generador LCD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mensaje enviar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(".asm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del archivo");

        jTextArchivo.addActionListener(this::jTextArchivoActionPerformed);

        jTextEnvio.addActionListener(this::jTextEnvioActionPerformed);

        btnExportar.setBackground(new java.awt.Color(0, 102, 102));
        btnExportar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        laHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laHora.setForeground(new java.awt.Color(255, 255, 255));
        laHora.setText("Hora envio");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Kit.png"))); // NOI18N

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laHora)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5))))
                                .addGap(125, 125, 125)
                                .addComponent(btnExportar)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laHora)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArchivoActionPerformed

    private void jTextEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnvioActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        String nombreArchivo = jTextArchivo.getText().trim();
    String mensaje = jTextEnvio.getText();

    if (nombreArchivo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingresa un nombre de archivo.",
                "Falta el nombre", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (mensaje.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingresa el mensaje que se enviará al LCD.",
                "Falta el mensaje", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int espaciosDisponibles = PUERTO_FINAL - PUERTO_INICIAL + 1;
    if (mensaje.length() > espaciosDisponibles) {
        JOptionPane.showMessageDialog(this,
                "El mensaje es muy largo para el LCD (máximo " + espaciosDisponibles + " caracteres).",
                "Mensaje demasiado largo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1. Generar el código y mostrarlo en el jTextArea
    String codigoAsm = generarCodigoLCD(mensaje, nombreArchivo);
    jTextArea.setText(codigoAsm);

    // 2. Guardarlo en la ruta fija
    try {
        File carpeta = new File(RUTA_DESTINO);
        if (!carpeta.exists()) {
            carpeta.mkdirs();
        }

        File archivo = new File(carpeta, nombreArchivo + ".asm");
        try (FileWriter escritor = new FileWriter(archivo)) {
            escritor.write(codigoAsm);
        }

        // 3. Actualizar la hora de envío
        String hora = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        laHora.setText("Hora envio: " + hora);

        JOptionPane.showMessageDialog(this,
                "Archivo guardado correctamente en:\n" + archivo.getAbsolutePath(),
                "Exportación exitosa", JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this,
                "Ocurrió un error al guardar el archivo:\n" + ex.getMessage(),
                "Error al guardar", JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnExportarActionPerformed
    
/**
 * Genera el código ensamblador que envía, carácter por carácter, el
 * mensaje al dispositivo "ASCII LCD Display Output" de emu8086
 * (puertos 2040h a 206Fh), usando OUT DX, AL.
 */
private String generarCodigoLCD(String mensaje, String nombreArchivo) {
    StringBuilder codigo = new StringBuilder();
    codigo.append("; JIMENEZ PEDRAZA OMAR GUADALUPE - PRUEBA LCD - GUARDAR COMO ")
          .append(nombreArchivo).append(".asm\n");
    codigo.append(".MODEL SMALL\n");
    codigo.append(".STACK\n");
    codigo.append(".DATA\n");
    codigo.append("    MENSAJE DB '").append(mensaje).append("'  ;LONG ")
          .append(mensaje.length()).append("\n");
    codigo.append(".CODE\n");
    codigo.append("    MOV AX,@DATA\n");
    codigo.append("    MOV DS,AX\n\n");
    codigo.append("    MOV SI,0 ; INDICE\n");
    codigo.append("    MOV CX,").append(mensaje.length()).append("\n");
    codigo.append(String.format("    MOV DX,%04XH  ; PUERTO INICIAL%n", PUERTO_INICIAL));
    codigo.append("\n");
    codigo.append("LABEL01:\n");
    codigo.append("    MOV AL,MENSAJE[SI]\n");
    codigo.append("    OUT DX, AL  ; ENVIAR HACIA EL PUERTO EL CONTENIDO DE <AL>\n");
    codigo.append("    INC SI\n");
    codigo.append("    INC DX\n");
    codigo.append("    LOOP LABEL01\n\n");
    codigo.append("    MOV AX, 4C00H\n");
    codigo.append("    INT 21H\n\n");
    codigo.append("END\n");

    return codigo.toString();
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLCD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextArchivo;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextEnvio;
    private javax.swing.JLabel laHora;
    // End of variables declaration//GEN-END:variables
}
